INSERT INTO "player" (first_name, last_name, position)
VALUES ('Randy', 'Brown', 'PG'),
       ('Jud', 'Buechler', 'SF'),
       ('Jason', 'Caffey', 'PF'),
       ('James', 'Edwards', 'C'),
       ('Jack', 'Haley', 'C'),
       ('Ron', 'Harper', 'PG'),
       ('Michael', 'Jordan', 'SG'),
       ('Steve', 'Kerr', 'PG'),
       ('Toni', 'Kukoč', 'SF'),
       ('Luc', 'Longley', 'C'),
       ('Scottie', 'Pippen', 'SF'),
       ('Dennis', 'Rodman', 'PF'),
       ('John', 'Salley', 'PF'),
       ('Dickey', 'Simpkins', 'PF'),
       ('Bill', 'Wennington', 'C');